---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$VENDOR/epigater
    - /bin/rm -rf $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -r * $DEPLOYPATH/
    - /bin/cp -r .git $DEPLOYPATH/
    - /bin/cp -r public $DEPLOYPATH/
    - /bin/cp -r src $DEPLOYPATH/
    - cd $DEPLOYPATH
    - npm install --production
    - npm run build
