---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$VENDOR/epigater
    - /bin/rm -rf $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -r * $DEPLOYPATH/
    - cd $DEPLOYPATH
    - npm install
    - npm run build
